spring.application.name=health-check-worker
spring.main.web-application-type=none

temporal.server.target=127.0.0.1:7233
engine.task-queue=orchestrator-task-queue
definition.service.url=http://localhost:8082
