spring.application.name=engine-api

server.port=8081

temporal.server.target=127.0.0.1:7233
engine.task-queue=orchestrator-task-queue

spring.datasource.url=jdbc:postgresql://localhost:5432/engine
spring.datasource.username=temporal
spring.datasource.password=temporal
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
